version: '2'
services:
    test_result_notifier-mysql:
        container_name: test_result_notifier-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/test_result_notifier/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=test_result_notifier
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
